homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    #path('profile/', views.profile, name='profile'),
    # dilanjutkan ...
]

myproject/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('homepage.urls')),
    path('', include('story3.urls')),
    path('',include('schedule.urls')),
    path('story6/',include('story6.urls')),
]

schedule/urls.py
from django.contrib import admin
from django.urls import path
from .views import schedule_index, schedule_create, remove_schedule, schedule_detail

urlpatterns = [
    path('schedule/', schedule_index, name='schedule' ),
    path('schedule-create/', schedule_create, name='scheduleCreate' ),
    path('schedule-detail/<int:id>', schedule_detail, name='scheduleDetail'),
    path('schedule-delete/<int:id>', remove_schedule, name="remove_schedule")
]

story3/urls.py
from django.urls import path
from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.index, name='profile'),
    path('halamanbaru/', views.profile, name='halamanbaru'),
]

story6/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.story6),
    path('post-kegiatan', views.post_kegiatan),
    path('post-peserta/<int:id_kegiatan>', views.post_peserta),
]

homepage/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models

# Create your models here.

class Schedule(models.Model) :
    kelas = models.CharField(max_length=80)
    dosen = models.CharField(max_length=40)
    jumlahsks = models.IntegerField()
    deskripsi = models.TextField(max_length=100)
    tempat = models.CharField(max_length=40)

    GANJIL = "Ganjil 2020/2021"
    GENAP = "Genap 2020/2021"
    TAHUN_CHOICES = [(GANJIL, 'Ganjil 2020/2021'), (GENAP, 'Genap 2020/2021')]
    tahun = models.CharField(max_length=16, choices=TAHUN_CHOICES, default="GENAP")

    

story3/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models


# Create your models here.
class Kegiatan(models.Model):
    nama = models.CharField(max_length=30)

    def __str__(self):
        return self.nama


class Peserta(models.Model):
    nama = models.CharField(max_length=30)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.nama

schedule/forms.py
from django import forms

class ScheduleForm(forms.Form) :
    kelas = forms.CharField(label="Kelas", max_length=80)
    dosen = forms.CharField(label="Nama Dosen", max_length=40)
    jumlahsks = forms.IntegerField(label="Jumlah SKS")
    deskripsi = forms.CharField(label="Deskripsi", max_length=100)
    tempat = forms.CharField(label="Ruang Kelas", max_length=40)

    GANJIL = "Ganjil 2020/2021"
    GENAP = "Genap 2020/2021"
    TAHUN_CHOICES = [(GANJIL, 'Ganjil 2020/2021'), (GENAP, 'Genap 2020/2021')]
    tahun = forms.ChoiceField(choices=TAHUN_CHOICES, label="Semester")

story6/forms.py
from django import forms


class KegiatanForm(forms.Form):
    nama_kegiatan = forms.CharField(label='Nama Kegiatan', max_length=64,
                                    widget=forms.TextInput(attrs={'class': 'form-control'}))


class PesertaForm(forms.Form):
    nama_peserta = forms.CharField(label='Nama Peserta', max_length=64,
                                   widget=forms.TextInput(attrs={'class': 'form-control'}))

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

schedule/views.py
from django.shortcuts import render, redirect
from .models import Schedule
from .forms import ScheduleForm
import datetime

# Create your views here.
def schedule_index(request, *args, **kwargs):
    my_form = ScheduleForm(Schedule)
    schedules =Schedule.objects.all()

    context = {
        'form' : my_form,
        'schedules' : schedules
    }
    return render(request, "schedule.html", context)  

def schedule_detail(request, id):
    schedule = Schedule.objects.get(id=id)
    context = {"schedule": schedule}
    return render(request, 'schedule_detail.html', context)

def schedule_create(request):
    my_form = ScheduleForm()

    if request.method == 'POST':
        my_form = ScheduleForm(request.POST)
        if my_form.is_valid():
            Schedule.objects.create(**my_form.cleaned_data)
            return redirect("schedule")

    context = {
        'form' : my_form,
    }
    return render(request, "schedule_create.html", context)  

def remove_schedule(request, id, *args, **kwargs):
    Schedule.objects.filter(id=id).delete()

    return redirect("schedule")  

story3/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'profile.html')

def profile(request):
    return render(request, 'halamanbaru.html')

story6/views.py
from django.shortcuts import render, redirect

from story6.forms import KegiatanForm, PesertaForm
from story6.models import Kegiatan, Peserta


# Create your views here.
def story6(request):
    datas = {
        'kegiatan': Kegiatan.objects.all(),
        'peserta': Peserta.objects.all(),
    }
    data_forms = {
        'kegiatan_form': KegiatanForm(),
        'peserta_form': PesertaForm(),
    }
    response = {
        'forms': data_forms,
        'data': datas
    }
    return render(request, 'story6.html', response)


def post_kegiatan(request):
    if request.method == 'POST':
        form = KegiatanForm(request.POST or None)
        if form.is_valid():
            data_form = form.cleaned_data
            data = Kegiatan(nama=data_form['nama_kegiatan'])
            data.save()
            return redirect('/story6/')
        else:
            return redirect('/story6/')
    else:
        return redirect('/story6/')


def post_peserta(request, id_kegiatan):
    if request.method == 'POST':
        form = PesertaForm(request.POST or None)
        if form.is_valid():
            kegiatan = Kegiatan.objects.get(id=id_kegiatan)
            data_form = form.cleaned_data
            data_input = Peserta()
            data_input.nama = data_form['nama_peserta']
            data_input.kegiatan = kegiatan

            data_input.save()
            return redirect('/story6/')
        else:
            return redirect('/story6/')
    else:
        return redirect('/story6/')

homepage/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style.css' %}"/>
    <title>Zahra's Profile</title>
    
</head>
    
<body bgcolor="#E6E6FA">
  <style>
      img {
          image-orientation: from-image;
          transform: (0deg);
          transition: 2s;
      }


      p,h1,h2,h3,h4,h5,h6,li {
          font-family:"Didot", "Perpetua", "Garamond", sans-serif ;
      }

      img:hover {
          transform: rotate(360deg);
      }

      #headline {
        height: 150px;
        background-color: paleturquoise;
        overflow: hidden;
        margin-bottom: 300px;
        padding: 10px 0 10px 10px;

      }

      #pendidikan {
          font-family: "Didot", "Perpetua", "Garamond", sans-serif;
          border-collapse: collapse;
          width: 30%;
      }

      #pendidikan th {
          border: 1px solid #ddd;
          padding: 20px;
      }

      #pendidikan tr:nth-child(even) {
          background-color: #f2f2f2;
      }

      #pendidikan tr:hover {
          background-color: #ddd;
      }

      #pendidikan th {
          padding-top: 20px;
          padding-bottom: 15px;
          text-align: center;
          background-color: #FBD255;
          color: white;
      }
  </style>
  <img src="{% static 'CODD2742.jpg'%}" width="275" height="350" alt="Jara dibunga matahari" style="margin:50px 490px">
  <div id = "slidshow"></div>
    <h3 align="center">
        About Me :
    </h3>
    <p align="center" style="font-size:145%;">Hello Everyone! Welcome to my first ever website. In this website you will be able to get to know a little bit of me.</p>
    <p align="center" style="font-size:125%" >sebelumnya perkenalkan nama saya <strong>Cut Zahra Nabila,</strong> you can call me Jara. Saat ini saya berkuliah di Universitas Indonesia jurusan Sistem Informasi angkatan 2019 dengan NPM 1906399934.Saya mengisi waktu dengan melakukan hobi-hobi saya, antara lain nonton film apapunn dan baca - baca novel.</p>
    
  </div>
  <table id="pendidikan" align="center">
      <tr>
          <th>Jenjang Pendidikan</th>
      </tr>
      <tr>
          <td>TK FITRIA</td>
      <tr>
          <td>SD ANGKASA 4</td>
      </tr>
      <tr>
          <td>SMPN 157 JAKARTA</td>
      </tr>
      <tr>
          <td>SMAN 67 JAKARTA</td>
      </tr>
      <tr>
          <td>Universitas Indonesia (S1 Sistem Informasi)</td>
      </tr>
  </table>

  <div id = "headline">
    <h3>Connect with me more on:</h3>
    <p>my instagram</p>
    <a href="https://www.instagram.com/zahrajaraaa/" target="_blank" title="Follow Me"><img border="0" src="https://1.bp.blogspot.com/-YgjDI7ryeCw/WBK0256tXeI/AAAAAAAAGwI/ENH2OyP7KUgQ9Q8Mix15YH8T_easIwguQCLcB/s1600/instagram.png" style="border: medium none; position: relative;" / />
  </div>
      

  </a>
</body>

</html>

schedule/templates/base.html
{% load static %}
<html>
    <head>
        <title>Schedule Zahra</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!--BOOTSTRAP CSS-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> <!--BOOTSTRAP SOSMED-->
        <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
        

        <!--FONT-->
        <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Alata|Alfa+Slab+One|Archivo+Black|Covered+By+Your+Grace|Gravitas+One|Noto+Sans|Passion+One|Rozha+One|Shrikhand&display=swap" rel="stylesheet">
        
        <!--CUSTOM CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">    
        <link rel="stylesheet" type="text/css" href="{% static 'scheduleStyle.css' %}"> 

    </head>
    <body>
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    </body>
</html>

schedule/templates/schedule.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="mainpage d-flex flex-column">

    <div class="d-flex flex-column mt-5 entries">
        {% for schedule in schedules %}
        <div class="card1 mb-4 mx-5 entry">
            <div class="card-header">
                {{schedule.tahun}}
            </div>
            <div class="card-body">
                <a href="{% url 'scheduleDetail' id=schedule.id %}"><h4 class="card-title">{{ schedule.kelas }}</h4></a>
                <p class="card-text">{{ schedule.tempat }}</p>
                <a href="{% url 'remove_schedule' schedule.id %}" class="card-link">REMOVE</a>
            </div>
        </div>
    <div class="mt-5 ml-5">
        <center><a class="button-class" role="button" href="{% url 'scheduleCreate' %}">Add a New Class</a></center>
    </div>
        {% endfor %}

    </div>

</div>

{% endblock content %}

schedule/templates/schedule_create.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="mainpage2"> 
        <div class="d-flex flex-column scheduleform">
            <h1 class="mt-3 add">Add a new class</h1>
            <form method="POST">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <input type="submit" class="button-submit mx-auto" value="SUBMIT">
            </form>
        </div>
        <div class="d-flex justify-content-center">
            <a role="button" class="button-create" href="{% url 'schedule' %}">VIEW CLASSES</a>
        </div>
</div>

{% endblock content %}

schedule/templates/schedule_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="mainpage2">
    <div class="container my-auto">
        <div class="jumbotron7">
            <h1 class="display-4">{{ schedule.kelas }}</h1>
            <p class="lead">{{ schedule.dosen }} </p>
            <p class="lead">{{ schedule.tempat }} </p>
            <p class="lead">{{ schedule.jumlahsks }} SKS</p>
            <p class="lead">{{ schedule.tahun }} </p>
            <hr class="my-4">
            <p> {{schedule.deskripsi}} </p>
            <p class="lead">
                <a class="btn btn-secondary btn-md" href="http://www.cs.ui.ac.id" role="button">Learn more</a>
            </p>
        </div>
    </div>
</div>

{% endblock content %}

story3/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>Zahra's Profile</title>
  
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    

    <!-- My CSS-->
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light">
        <div class= "container"></div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml">
                <a class="nav-link" href="{% url 'story3:profile'%}#Home">Home</a>
                <a class="nav-link" href="{% url 'story3:profile'%}#skill">skill</a>
                <a class="nav-link" href="{% url 'story3:profile'%}#experience">experience</a>
                <a class="nav-link active" href="{% url 'story3:profile'%}#headline">contact</a>
                
            </div>
            </div>
        </div>
        </nav>
        {% block content %} {% endblock %}
    </body>
</html>

story3/templates/profile.html
{% extends 'navbar.html'%} 
{% load static %} {% block content %}

    <!-- Akhir navbar -->
    <!-- Jumbotron -->
    <div class="jumbotron jumbotron-fluid" id ="Home">
      <div class="container">
        <h1 class="display-4">Hello!</h1>
        <br>
        <h2>I'm Zahra Nabila</h2>
        <p class="lead">Student University of Indonesia</p>
        <br>
        <button type="button" class="btn btn-secondary"  onclick="location.href='#about'">About Me</button>
      </div>
    </div>

    <div class="jumbotron1 jumbotron-fluid" id ="about">
      <div class="slide2"></div>
        <h1 class="text-center">ABOUT ME</h1>
        <br>
        <p class="text-center">I'm a happy person and like everthing related to mystery.</p>
        <p class="text-center">I'd like to see movie to spend my time and i really enjoy.</p>
        <p class="text-center">my favorite movie in the world.</p>
        <center><a id="nav" href="{% url 'story3:halamanbaru' %}">Go check</a></center>
      </div>
    </div>

    <div class="jumbotron2 jumbotron-fluid" id="experience">
      <div class="container">
        <div class="row">
          <div class="col-6">
            <div class="card-img">
            </div>     
          </div>
          <div class="col-6">
            <div class="card-img">
              <h1 style="text-align: center;">EXPERIENCE</h1>
              <br>
              <img class="card-img rounded" src="{% static 'Gambar2.png' %}" alt="Sheep 9">
              <div class="card-img-overlay text-white d-flex justify-content-center align-items-end">
                <p style=" text-align :center ; padding-bottom: 80px; padding-left: 20px; padding-right: 20px;">Staff Media partner of COMPFEST12 , Staff Event of BETIS 2020 , Manager of Shopee</p>
          </div>
        </div>
      </div>
    </div>

    <div class="jumbotron3 jumbotron-fluid" id = "skill">
      <div class="container">
        <div class="row">
          <div class="col-6">
            <div class="card-img">
                <h1 style ="text-align: center;">SKILL</h1>
                <br>
                <img class="card-img rounded" src="{% static 'Gambar1.png' %}"  alt="Sheep 9">
                <div class="card-img-overlay text-white d-flex justify-content-center align-items-end">
                  <p style="text-align:center; padding-bottom: 80px;">Communication - Computer skill - Management skills. </p>
                </div>
            </div>     
          </div>
          <div class="col-6">
          </div>
        </div>
      </div>
    </div>

    <div id = "headline">
      <h3 style="text-align: center;">Connect with me more on:</h3>
      <a href="https://www.instagram.com/zahrajaraaa/" target="_blank" title="Follow Me">
      <center><img border="0" src='https://1.bp.blogspot.com/-YgjDI7ryeCw/WBK0256tXeI/AAAAAAAAGwI/ENH2OyP7KUgQ9Q8Mix15YH8T_easIwguQCLcB/s1600/instagram.png' style="border: medium none; position: relative;" / /></center>
    </div>
  

    <!-- akhir jumbrotron -->
    


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {% endblock %}

story6/templates/story6.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href='{% static "/story6.css" %}'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Story 6</title>
</head>
<body>
<div>
    <form id="form" method="POST" action="/story6/post-kegiatan" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ forms.kegiatan_form.as_p }}
        </div>
        <br>
        <button type="submit" class="btn btn-warning" id="bton">Tambah Kegiatan</button>
    </form>
</div>
<br><br>

{% for kegiatan in data.kegiatan %}
    <div class="card border-dark mb-3" style="max-width: 18rem; text-align: center; margin: 0 auto;
        float: none;
        margin-bottom: 10px;">
        <div class="card-header">{{ kegiatan.nama }}</div>
        <div class="card-body text-dark">
            <h5 class="card-title">Peserta : </h5>
            {% for peserta in data.peserta %}
                {% if peserta.kegiatan.nama == kegiatan.nama %}
                    <p class="card-text">{{ peserta.nama }}</p>
                {% endif %}
            {% endfor %}
        </div>
        <form id="form" method="POST" action="/story6/post-peserta/{{ kegiatan.id }}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ forms.peserta_form.as_p }}
            </div>
            <br>
            <button type="submit" class="btn btn-warning" id="bton">Tambah Peserta</button>
        </form>
    </div>
{% endfor %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>